INSERT INTO EXERCICIOS VALUES (EXERCICIOS_CODIGO_EXERCICIO_SEQ.NEXTVAL,12,'BICEPS ROSCA','A');
INSERT INTO EXERCICIOS VALUES (EXERCICIOS_CODIGO_EXERCICIO_SEQ.NEXTVAL,12,'BICEPS BANCO','A');
INSERT INTO EXERCICIOS VALUES (EXERCICIOS_CODIGO_EXERCICIO_SEQ.NEXTVAL,12,'BICEPS CORDA','A');

INSERT INTO ALUNOS VALUES ('167.636.337.85','BRAYAN BAUTZ','A',TO_DATE('02/04/2022','DD/MM/YYYY'),NULL,27998863543);