SELECT COUNT(1) AS TOTAL_FAVORITOS, E.NOME_EXERCICIO
FROM ALUNOS A
INNER JOIN EXERCICIOS E
ON A.ALUNOS_EXERCICIOS = E.CODIGO_EXERCICIO group by E.NOME_EXERCICIO;

SELECT NOME_ALUNO FROM ALUNOS
WHERE upper(pagamento) LIKE UPPER('%i%')
group by nome_aluno