select codigo_exercicio, nome_exercicio, repeticoes, grupo_muscular from exercicios where nome_exercicio = 'polichinelo';

select cpf, nome_aluno, telefone, pagamento, vencimento_mensalidade, alunos_exercicios from alunos where cpf = '167.636.337-85';

select e.codigo_exercicio
                    , e.nome_exercicio 
                from exercicios e
                order by e.nome_exercicio;
select cpf, nome_aluno, telefone, pagamento, vencimento_mensalidade, alunos_exercicios from alunos where cpf = '167.636.337-85';

INSERT INTO ALUNOS VALUES ('954.206.637-67','Pedro Henrique Bruno Danilo da Rosa','A',28,1,27984317939);
INSERT INTO ALUNOS VALUES ('271.716.287-95','Benício Bryan Sales','A',25,3,27984536300);
INSERT INTO ALUNOS VALUES ('754.213.007-22','Arthur Luís Silva','A',27,1,27983320915);
INSERT INTO ALUNOS VALUES ('277.716.817-27','Francisco Kaique Victor Silveira','A',30,2,27992422949);

INSERT INTO ALUNOS VALUES ('678.856.887-12','Antônia Patrícia Juliana Drumond','I',30,2,28999628749);
INSERT INTO ALUNOS VALUES ('015.744.507-00','Jorge Tomás Noah Santos','I',8,1,27982094019);

INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,0,'A','A');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,0,'B','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,0,'C','C');

INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Voador','A');
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Supino inclinado com barra','A');
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Crucifixo reto','A');
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Supino reto com barra','A');
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,10,'Tríceps Voador','A');
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,10,'Tríceps Corda Cross','A');
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Polichinelo','A'); 
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,10,'Flexão','A');
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Tríceps Barra Cross','A');
INSERT INTO EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Tríceps Testa','A');

INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Levantamento terra','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Pulley Frontal','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Pulley Atrás','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Remada Baixa','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Serrote','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,10,'Rosca Alternada com Banco inclinado','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Rosca Scott barra W','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,10,'Rosca direita barra Reta','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Martelo em pé','B');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Rosca Punho','B');

INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Leg press 45º','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Extensor de pernas','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,10,'Flexora Sentada','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Adutora','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Abdutora','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Stiff','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Desenvolvimento nuca com Barra','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,12,'Desenvolvimento Maquina','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Elevação frontal com halteres em pé','C');
INSERT INTO	EXERCICIOS VALUES (CODIGO_EXERCICIOS_SEQ.NEXTVAL,11,'Elevação lateral com halteres sentado','C');