SELECT  E.GRUPO_MUSCULAR, E.NOME_EXERCICIO, E.REPETICOES FROM EXERCICIOS E
INNER JOIN ALUNOS A ON E.CODIGO_EXERCICIO = A.CODIGO_EXERCICIO
WHERE CODIGO_ALUNO = :CODIGO_ALUNO
AND ROWNUM < 8
ORDER BY DBMS_RANDOM.VALUE