ALTER TABLE LABDATABASE.ALUNOS DROP CONSTRAINT CPF_ALUNO;
ALTER TABLE LABDATABASE.ALUNOS DROP CONSTRAINT EXERCICIOS_ALUNOS_FK;
ALTER TABLE LABDATABASE.EXERCICIOS DROP CONSTRAINT EXERCICIOS_PK;

DROP TABLE LABDATABASE.EXERCICIOS;
DROP TABLE LABDATABASE.ALUNOS;

DROP SEQUENCE LABDATABASE.CODIGO_EXERCICIOS_SEQ;

CREATE TABLE LABDATABASE.Exercicios (
                Codigo_Exercicio NUMBER NOT NULL,
                Repeticoes NUMBER NOT NULL,
                Nome_Exercicio VARCHAR2(100) NOT NULL,
                Grupo_Muscular CHAR(1) NOT NULL,
                CONSTRAINT EXERCICIOS_PK PRIMARY KEY (Codigo_Exercicio)
);


CREATE TABLE LABDATABASE.Alunos (
                Cpf VARCHAR2(15) NOT NULL,
                Nome_Aluno VARCHAR2(100) NOT NULL,
                Pagamento CHAR NOT NULL,
                Vencimento_Mensalidade numeric(2) NOT NULL,
                Alunos_Exercicios NUMBER(8),
                Telefone NUMBER(11) NOT NULL,
                CONSTRAINT CPF_ALUNO PRIMARY KEY (Cpf)
);

ALTER TABLE LABDATABASE.Alunos ADD CONSTRAINT EXERCICIOS_ALUNOS_FK
FOREIGN KEY (alunos_exercicios)
REFERENCES LABDATABASE.Exercicios (Codigo_Exercicio)
NOT DEFERRABLE;

CREATE SEQUENCE LABDATABASE.CODIGO_EXERCICIOS_SEQ
MINVALUE 1
START WITH 1;

GRANT ALL ON LABDATABASE.EXERCICIOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.ALUNOS TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;

COMMIT;